name: create pr

on:
  push:
    branches:
      - data

jobs:
  pr-development:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
          path: data-branch
      - uses: actions/checkout@v2
        with:
          ref: development
          path: development
      - run: |
          cp -rf data-branch/data/* development/data/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: development
          commit-message: UPDATE DATA
          title: UPDATE DATA
          base: development
          branch: data-bot/development
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
 